ruppeshapp/urls.py
from django.conf.urls import url 
from .views import *


urlpatterns = [

    url(r'^school-admin/logout/$', AdminLogout.as_view(),
        name='adminlogout'),
    url(r'^school-admin/login/$', AdminLogin.as_view(),
        name='adminlogin'),




    url(r'^school-admin/$', AdminHomeView.as_view(), name='adminhome'),
    url(r'^school-admin/school/create/$',
        AdminOrganizationCreateView.as_view(), name='adminorganizationcreate'),
    url(r'^school-admin/school/(?P<pk>\d+)/update/$',
        AdminOrganizationUpdateView.as_view(), name='adminorganizationupdate'),


    # client
    url(r'^$', ClientHomeView.as_view(), name='clienthome'),
    

       ]

ruppeshproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ruppeshapp.urls', namespace='ruppeshapp'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ruppeshapp/models.py
from django.db import models
from django.utils import timezone


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()




class Organization(TimeStamp):
    name = models.CharField(max_length=255)
    established_date = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    phone2 = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=500)
    image = models.ImageField(upload_to='orgimage/', null=True, blank=True)
    logo = models.ImageField(upload_to="logo/")
    description = models.TextField()
    slogan = models.CharField(max_length=1024, null=True, blank=True)

    def __str__(self):
        return self.name



class Message(TimeStamp):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.PositiveIntegerField(null=True, blank=True)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name

ruppeshapp/forms.py
from django import forms
from .models import *



class DateTimeInput(forms.DateInput):
    input_type = 'time'


class AdminLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}))



class AdminOrganizationCreateForm(forms.ModelForm):
    class Meta:
        model = Organization
        exclude = ['created_at', 'updated_at', 'deleted_at']

    def __init__(self, *args, **kwargs):
        super(AdminOrganizationCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})



class MessageForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Write Your Name.'
            }))
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Write Your Phone Number.'
            }))
    subject = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Write Your Subject.'
            }))
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'Write Your Email.'
            }))
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'placeholder': 'Write Your message.'
            }))
    class Meta:
        model = Message
        fields = ['name', 'phone', 'email', 'subject', 'message']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminMessageDeleteForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }

ruppeshapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import *
from .models import *
from .forms import *


class AdminLogout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class AdminLogin(FormView):
    template_name = "ruppeshapp/admintemplates/adminlogin.html"
    form_class = AdminLoginForm
    success_url = '/school-admin/'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_superuser:
            login(self.request, user)
        else:
            return render(self.request, self.template_name, {
                'form': form,
                'errors': 'Incorrect username or password'})
        return super().form_valid(form)





class AdminMixin(LoginRequiredMixin, object):
    login_url = '/school-admin/login/'

    def get_context_data(self, *args, **kwargs):
        context = super(AdminMixin, self).get_context_data(*args, **kwargs)
        context['organization'] = Organization.objects.get(id=1)
        return context


class DeleteMixin(LoginRequiredMixin, UpdateView):
    login_url = '/school-admin/login/'

    def form_valid(self, form):
        form.instance.deleted_at = timezone.now()
        form.save()
        return super().form_valid(form)

class AdminHomeView(AdminMixin, TemplateView):
    template_name = 'ruppeshapp/admintemplates/adminhome.html'

class AdminOrganizationCreateView(AdminMixin, CreateView):
    template_name = 'ruppeshapp/admintemplates/adminorganizationcreate.html'
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('ruppeshapp:adminhome')


class AdminOrganizationUpdateView(AdminMixin, UpdateView):
    template_name = 'ruppeshapp/admintemplates/adminorganizationcreate.html'
    model = Organization
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('ruppeshapp:adminhome')


    # client


class ClientMixin(object):
    def get_context_data(self, *args, **kwargs):
        context = super(ClientMixin, self).get_context_data(*args, **kwargs)
        context['organization'] = Organization.objects.get(id=1)
        


class ClientHomeView(ClientMixin, CreateView):
    template_name='ruppeshapp/clienttemplates/clienthome.html'
    form_class = MessageForm
    success_url = '/'

templates/ruppeshapp/admintemplates/adminhome.html
{% extends 'ruppeshapp/admintemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}


{% block content %}
<div class="container-fluid bg-light">
	{% if organization %}
    <div class="content">
        <h2 style="color: green;"><img src="{{organization.logo.url}}" width="100" style="border: 4px solid red;">{{organization.name|striptags}}, &nbsp;<small>"{{organization.slogan}}"</small></h2>
        <a href="{% url 'ruppeshapp:adminorganizationupdate' organization.id %}" class="btn btn-primary pull-right">Update Organization</a>
        <hr>

        <h5>{{organization.location}}</h5>
        <h5>{{organization.established_date}}</h5>
        <h5>{{organization.phone1}}</h5>
        <h5>{{organization.phone2}}</h5>
        <h5>{{organization.email}}</h5>
    </div>
    <div class="row clearfix">
    	<img src="{{organization.image.url}}" class="img-responsive">
    	 <p>{{organization.description|safe}}</p>
    </div>
    <a href="{% url 'ruppeshapp:adminorganizationupdate' organization.id %}" class="btn btn-primary pull-right">Update Organization</a><hr><br><br>
    {% else %}
    <div class="row clearfix">
    	<a href="{% url 'ruppeshapp:adminorganizationcreate' %}">Create Organization</a>
    </div>


    {% endif %}
</div>
{% endblock content %}

templates/ruppeshapp/admintemplates/adminlogin.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<head>
    <title>{% block title %}Login{% endblock title %}</title>
    <link rel="icon" href="{% static 'adminstatic/images/favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'adminstatic/plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
</head>
</head>
<body class="container">
<div class="row">
	<div class="col-md-4 col-md-offset-4 bg-primary">
		<h3 class="text-center">Administration Login</h3><hr>
		
		{% if errors %}
		<h3 style="color: red;">{{errors}}</h3>
		{% else %}
		<h3>Enter your secret username and password</h3>
		{% endif %}
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<br>
			<button class="btn btn-block btn-default">Submit</button>
		</form><br>
	</div>
</div>	
</body>
</html>

templates/ruppeshapp/admintemplates/adminorganizationcreate.html
{% extends 'ruppeshapp/admintemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home%}


{% block content %}
<div class="container-fluid">
    <div class="block-header">
        <h2>Create or Update Organization</h2>
    </div>

    <div class="row clearfix">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button class="btn btn-primary">Submit</button>
        </form>
        <hr>
    </div>
</div>
{% endblock content %}

templates/ruppeshapp/clienttemplates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Head -->
<head>
<title>Professional CV a Personal Category Bootstrap Responsive Website Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="Professional CV a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

<!-- menu -->
<link type="text/css" rel="stylesheet" href="{% static 'clientstatic/css/cm-overlay.css' %}" />
<!-- //menu -->
<link href="{% static 'clientstatic/css/jquery.fatNav.css' %}" rel="stylesheet" type="text/css">

<!--FlexSlider-->
	<link rel="stylesheet" href="{% static 'clientstatic/css/flexslider.css' %}" type="text/css" media="screen" />
<!--//FlexSlider-->

<link rel="stylesheet" href="{% static 'clientstatic/css/lightbox.css' %}"><!-- For-gallery-CSS -->

<!-- custom css theme files -->
	<link rel="stylesheet" href="{% static 'clientstatic/css/bootstrap.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'clientstatic/css/font-awesome.min.css' %}" />
	<link rel="stylesheet" href="{% static 'clientstatic/css/style.css' %}" type="text/css" media="all">
<!-- //custom css theme files -->

<!-- google fonts -->
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet">
<!-- //google fonts -->

</head>
<!-- Body -->
<body id="home">
<!-- banner -->
	<nav class="w3-navbar">
					<div class="container">
						<div class="nav-top">
						
							  <!-- Logo -->
								<div class="logo">
								  <a href="#home" class="scroll">
									Professional <span>CV</span>
								  </a>
							  </div>
							  <!-- Logo -->
							<div class="right">
								<div class="w3-socials">
									<ul>
										<li>
											<a href="https://www.facebook.com/ruppesh.adhikari.1"><span class="fa fa-facebook"></span></a>
										</li>
										<li>
											<a href="https://twitter.com/RuppeshA"><span class="fa fa-twitter"></span></a>
										</li>
									</ul>
								</div>
								<div class="clearfix"></div>
							</div>
						</div>
						
					</div> <!-- end container -->
				
	</nav>
	
<div class="w3l-banner">
<div class="wthree-dot">

	<!-- nav -->
	<div class="w3layouts-nav-right">
		<div class="fat-nav">
			<div class="fat-nav__wrapper">
				<ul>
					<li><a href="index.html" >Home</a></li>
					<li><a href="#about"  class="scroll" >About Me</a></li>
					<li><a href="#services"  class="scroll" >My Services</a></li>
					<li><a href="#skills"  class="scroll" >My Skills</a></li>
					<li><a href="#gallery"  class="scroll" >My projects</a></li>
					<li><a href="#stats"  class="scroll" >Stats</a></li>
					<li><a href="#experience"  class="scroll" >Work Experience</a></li>
					<li><a href="#contact"  class="scroll" >Contact</a></li>
				</ul>
			</div>
		</div>
	</div>		
	<!-- //nav -->
	
		<!-- //Header -->
		<div class="container">
			<div class="flexslider-info">
				<section class="slider col-md-6">
					<div class="flexslider">
						<ul class="slides">
							<li>
							<div class="w3l-info">
								<h1>Hi myself <span>Ruppesh</span></h1>
								<p>Hello friends wats up i am ruppesh adhikari an Electronics and Communication
								Engineer & i am from malangwa. </p>
								<ul>
									<li><a href="#" class="w3ls_more" >Hire Me</a></li>
									<li><a href="#contact" class="scroll w3l_contact">Contact Me</a></li>
								</ul>
							</div>
							</li>
							<li>
								<div class="w3l-info">
								<h2>this is my <span>website</span></h2>
								<p>This my Professional CV Website and love to build a website of different types as much as more quickly and efficient</p>
								<ul>
									<li><a href="#" class="w3ls_more" >Hire Me</a></li>
									<li><a href="#contact" class="scroll w3l_contact">Contact Me</a></li>
								</ul>
								</div>
							</li>
							<li>
								<div class="w3l-info">
								<h3>I'm a <span>Django Programmer</span></h3>
								<p>Being a website designer i also love to do programming, this is my hobby also</p>
								<ul>
									<li><a href="#" class="w3ls_more">Hire Me</a></li>
									<li><a href="#contact" class="scroll w3l_contact">Contact Me</a></li>
								</ul>
								</div>
							</li>
						</ul>
					</div>
				</section>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
</div>
{% block content %}

{% endblock content %}


	<!--//footer -->


<!-- Default-JavaScript-File -->
	<script type="text/javascript" src="{% static 'clientstatic/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'clientstatic/js/bootstrap.min.js' %}"></script>
<!-- //Default-JavaScript-File -->

<!-- gauge-meter -->
	<script src="{% static 'clientstatic/js/jquery.gauge.js' %}"></script>
	<script>
		$(document).ready(function (){
			$("#gauge1").gauge(90,{color: "#ff4f81",unit: " %",type: "halfcircle"});
			$("#gauge2").gauge(70, {color: "#2dde98", unit: " %",type: "halfcircle"});
			$("#gauge3").gauge(75, {color: "#00aeff",unit: " %",type: "halfcircle"});
			$("#gauge4").gauge(40, {color: "#ffb900",unit: " %",type: "halfcircle"});
		});
	</script>
<!-- //gauge-meter -->

<!--menu script-->
<script type="text/javascript" src="{% static 'clientstatic/js/modernizr-2.6.2.min.js' %}"></script>
		<script src="{% static 'clientstatic/js/jquery.fatNav.js' %}"></script>
		<script>
		(function() {
			
			$.fatNav();
			
		}());
		</script>

<!--Start-slider-script-->
	<script defer src="{% static 'clientstatic/js/jquery.flexslider.js' %}"></script>
		<script type="text/javascript">
		
		$(window).load(function(){
		  $('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
			  $('body').removeClass('loading');
			}
		  });
		});
	  </script>
<!--End-slider-script-->

<!-- smooth scrolling -->
	<script src="{% static 'clientstatic/js/SmoothScroll.min.js' %}"></script>
<!-- smooth scrolling -->

<!-- scrolling script -->
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script> 
<!-- //scrolling script -->
	
	
</body>
<!-- //Body -->
</html>

templates/ruppeshapp/clienttemplates/test.html
<!DOCTYPE html>
<html>
<head>
	<title>test</title>
</head>
<body>
<div class="gallery" id="gallery">
	<div class="container">
		
			<h2 class="text-center">gallery</h2>
			<h3 class="text-center">My skills</h3>
			<div class="col-md-10 gallery-left-grid">
				<h1>erugueg</h1>
				<P>fgeyf</P>
				
			</div>
			
		
	</div>
</div>
</body>
</html>